Veewee::Session.declare({
  :boot_cmd_sequence => [
    '<Esc><Esc><Enter>',
    '/install/vmlinuz noapic preseed/url=http://%IP%:%PORT%/preseed.cfg ',
    'debian-installer=en_US auto locale=en_US kbd-chooser/method=us ',
    'hostname=%NAME% ',
    'fb=false debconf/frontend=noninteractive ',
    'console-setup/ask_detect=false console-setup/modelcode=pc105 console-setup/layoutcode=us ',
    'initrd=/install/initrd.gz -- <Enter>'
   ],
  :boot_wait => "10",
  :cpu_count => '1',
  :disk_size => '10140',
  :disk_format => 'VDI',
  :hostiocache => 'off',
  :iso_file => "ubuntu-10.04.2-server-i386.iso",
  :iso_src => "http://releases.ubuntu.com/10.04.2/ubuntu-10.04.2-server-i386.iso",
  :iso_md5 => "9807160b8935289096df8160832e358e",
  :iso_download_timeout => "1000",
  :kickstart_file => "preseed.cfg",
  :kickstart_port => "7122",
  :kickstart_timeout => "10000",
  :memory_size=> '384', 
  :os_type_id => 'Ubuntu',
  :postinstall_files => [ "postinstall.sh"],
  :postinstall_timeout => "10000"
  :ssh_login_timeout => "10000",
  :ssh_user => "vagrant",
  :ssh_password => "vagrant",
  :ssh_key => "",
  :ssh_host_port => "7222",
  :ssh_guest_port => "22",
  :sudo_cmd => "echo '%p'|sudo -S sh '%f'",
  :shutdown_cmd => "shutdown -P now",
})
